config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
    # collection do
    #   get 'sold_items'
    # end
  resources :credit_cards, only: [:new, :create, :show, :destroy]
  resources :categories, only:[:index]
  root 'items#index'
  resources :items do
    collection do
    get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :purchases, only: [:new, :create]
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :card_id, presence: true
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"
  before_action :set_card, except: [:new, :create]

  def new
    @card = CreditCard.where(user_id: current_user.id)
    redirect_to credit_card_path(current_user.id) if @card.exists?
  end

  def create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params["payjp_token"].blank?
      redirect_to new_credit_card_path, alert: 'クレジットカード情報を正しく入力してください'
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp_token"],
        metadata: {user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to credit_card_path(current_user.id), notice: 'クレジットカードの登録が完了しました'
      else
        redirect_to action: "create"
      end
    end
  end

  def show
    
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "visacard.svg"
      when "JCB"
        @card_src = "jcbcard.svg"
      when "MasterCard"
        @card_src = "mastercard.svg"
      when "American Express"
        @card_src = "amexcard.svg"
      when "SaisonCard"
        @card_src = "saisoncard.svg"
      end
      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
    end
  end

  def destroy
    
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      unless @card.destroy
        redirect_to credit_card_path(current_user.id)
      end
    end
  end
  
  private

  def set_card
    @card = CreditCard.find_by(user_id: current_user.id)
  end

end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/destroy.html.haml
.AccountPage
  = render "/devise/registrations/head_logo"
  .destroy
    .destroy__frame
      .destroy__frame--message
        削除が完了しました。
      %ul.destroy__frame--btns
        %li.my_page_link
          = link_to "マイページに戻る", users_path(current_user.id), class: "my_page_link__btn"
        %li.credit_card_new_link
          = link_to "クレジットカード新規登録", new_credit_card_path, class: "credit_card_new_link__btn"
  .AccountPage__etc
    = render "/devise/registrations/foot_logo"

app/views/credit_cards/new.html.haml
.AccountPage
  = render "/devise/registrations/head_logo"
  - breadcrumb :new_credit_card
  = render "layouts/breadcrumbs"
  .partContainer
    = render "users/side_bar"
    .creditcardArea
      %section.headerContainer
        %h2.headerTitle
          クレジットカード情報入力
      .formArea
        = form_tag(credit_cards_path, method: :post, id: "charge-form", class: "details", name: "inputForm") do
          .container
            .formBlock
              .formBlock__contents
                カード番号
                %span
                  必須
              = text_field_tag 'payment_card_no', "", class: 'formBlock__input', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
              = image_tag 'visacard.svg'
              = image_tag 'mastercard.svg'
              = image_tag 'saisoncard.svg'
              = image_tag 'jcbcard.svg'
              = image_tag 'amexcard.svg'
            .formBlock
              .formBlock__contents
                有効期限
                %span
                  必須
            .formBlockB
              .formBlockB__contents
                %select#payment_card_month.formBlockB__contents--select{name: "payment_card_month", type: "text"}
                  %option{ value: "1"}01
                  %option{ value: "2"}02
                  %option{ value: "3"}03
                  %option{ value: "4"}04
                  %option{ value: "5"}05
                  %option{ value: "6"}06
                  %option{ value: "7"}07
                  %option{ value: "8"}08
                  %option{ value: "9"}09
                  %option{ value: "10"}10
                  %option{ value: "11"}11
                  %option{ value: "12"}12
              .formBlockB__text
                月
              .formBlockB__contents
                %select#payment_card_year.formBlockB__contents--select{name: "payment_card_year", type: "text"}
                  %option{ value: "20"}20
                  %option{ value: "21"}21
                  %option{ value: "22"}22
                  %option{ value: "23"}23
                  %option{ value: "24"}24
                  %option{ value: "25"}25
                  %option{ value: "26"}26
                  %option{ value: "27"}27
                  %option{ value: "28"}28
                  %option{ value: "29"}29
                  %option{ value: "30"}30
              .formBlockB__text
                年

            .formBlock
              .formBlock__contents
                セキュリティコード
                %span
                  必須
              = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'formBlock__input', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
          .formArea__contents
            = submit_tag "追加する", class: "formArea__contents--box", id: "payment_card_submit-button"
            .backlinkArea
              = link_to "もどる", users_path, class: "back_link"
  .AccountPage__etc
    = render "/devise/registrations/foot_logo"

app/views/credit_cards/show.html.haml
.AccountPage
  = render "/devise/registrations/head_logo"
  .show
    = render "users/side_bar"
    .show__frame
      .show__frame--title
        登録クレジットカード情報
      .credit_card__list
        .credit_card__list--frame
          .credit_card_info
            .credit_card_info__brand
              = image_tag "#{@card_src}", class: "credit_card_info__brand--img", alt: @card_brand
            .credit_card_info__numbers
              .number
                = "**** **** **** " + @customer_card.last4
              .expiration_date
                .expiration_date__title
                  有効期限
                .expiration_date__info
                  = @exp_month + " / " + @exp_year
          .destroy__function
            .destroy__function--link
              = link_to credit_card_path, method: :delete, class: "destroy_btn" do 
                削除する
  .AccountPage__etc
    = render "/devise/registrations/foot_logo"