config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
    # collection do
    #   get 'sold_items'
    # end
  resources :credit_cards, only: [:new, :create, :show, :destroy]
  resources :categories, only:[:index]
  root 'items#index'
  resources :items do
    collection do
    get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :purchases, only: [:new, :create]
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require "payjp"
  before_action :set_purchase, only: [:new, :create]
  before_action :user_check, only: [:new ]
  def new
    
    if current_user.credit_card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      @card = CreditCard.find_by(user_id: current_user.id)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "visacard.svg"
      when "JCB"
        @card_src = "jcbcard.svg"
      when "MasterCard"
        @card_src = "mastercard.svg"
      when "American Express"
        @card_src = "amexcard.svg"
      when "SaisonCard"
        @card_src = "saisoncard.svg"
      end
        @exp_month = @customer_card.exp_month.to_s
        @exp_year = @customer_card.exp_year.to_s.slice(2,3)
      else
        redirect_to new_credit_card_path, alert: "クレジットカードを登録してください"
      end
  end

  def create
    
    if @item.purchase.present?
      redirect_to item_path(@item.id), alert: "売り切れています。"
    else
      @item.with_lock do
        if current_user.credit_card.present?
          @card = CreditCard.find_by(user_id: current_user.id)
          Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
          charge = Payjp::Charge.create(
          amount: @item.price,
          customer: Payjp::Customer.retrieve(@card.customer_id),
          currency: 'jpy'
          )
        else
      
        end
      @purchase = Purchase.create(user_id: current_user.id, item_id: params[:item_id])
      end
    end
  end

  private

  def set_purchase
    @item = Item.find(params[:item_id])
  end
  def user_check
    unless user_signed_in?
      redirect_to new_user_session_path, alert: "ログインしてください"
    end
  end

end

app/views/purchases/_item_info.html.haml
.item_info_box
  .item_info
    .item_info__image
      = image_tag (@item.images[0].src.url), class: "image-src"
    .item_info__status
      .item_info__status__name
        = @item.name
      .item_info__status__price
        %span.tax
          送料込み（税込）
        %span.price
          ¥
          = @item.price

app/views/purchases/create.html.haml
.AccountPage
  = render "/devise/registrations/head_logo"
  .buy
    .buy__flame
      購入が完了しました
    .buy__confirmation
      購入商品
    = render "item_info", item:@item, images:@images
    %ul.link_byn_flame
      %li.top_page_link
        = link_to "トップページに戻る", root_path, class: "top_page_link__btn"
      %li.buy_list
        = link_to "購入商品一覧", "#", class: "buy_list__btn"
  .AccountPage__etc
    = render "/devise/registrations/foot_logo"

app/views/purchases/new.html.haml
.AccountPage
  = render "devise/registrations/head_logo"
  .ConfirmPurchaseDetailsArea
    %section.contents
      %h2.contents__headerTitle
        購入内容の確認
    = render "item_info", item:@item, images:@images
    %section.contents
      .contents__payment
        %span.contents__payment--paymentAmount
          支払い金額
        %span.contents__payment--money
          ¥
          = @item.price
    .credit_card_text
      .credit_card_text__box
        登録クレジットカード情報
    .credit_card__list
      .credit_card__list--frame
        .credit_card_info
          .credit_card_info__brand
            = image_tag "#{@card_src}", class: "credit_card_info__brand--img", alt: @card_brand
          .credit_card_info__numbers
            .number
              = "**** **** **** " + @customer_card.last4
            .expiration_date
              .expiration_date__title
                有効期限
              .expiration_date__info
                = @exp_month + " / " + @exp_year
    .confirm_btn
      .confirm_btn__box
        = link_to "購入する", item_purchases_path(item_id: @item.id), class: "confirm_btn__box__buy", method: :post
    -# %section.contents
    -#   .contents__paymentMethod
    -#     %h3.contents__paymentMethod--methodOfPayment
    -#       支払い方法
    -#     %p.contents__paymentMethod--change
    -#       変更する
    -#       = link_to '#', class: 'angle-right' do
    -#         = icon('fas', 'angle-right')
    -# %section.contents
    -#   .contents__shippingAddress
    -#     %h3.contents__shippingAddress--destination
    -#       配送先
    -#     %p.contents__shippingAddress--change
    -#       変更する
    -#       = link_to '#', class: 'angle-right' do
    -#         = icon('fas', 'angle-right')
    -# %section.contents
    -#   %input.contents__box{ type:"submit", value:"購入する" }
  .AccountPage__etc
    = render "devise/registrations/foot_logo"