config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
    # collection do
    #   get 'sold_items'
    # end
  resources :credit_cards, only: [:new, :create, :show, :destroy]
  resources :categories, only:[:index]
  root 'items#index'
  resources :items do
    collection do
    get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :purchases, only: [:new, :create]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :category
  belongs_to_active_hash :itemcondition
  belongs_to_active_hash :postage
  belongs_to_active_hash :district
  belongs_to_active_hash :preparation

  belongs_to :user, optional: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_one :purchase  

  validates :images, presence: { message: 'を１枚以上アップロードしてください' }
  validates :name, presence: true, length: { maximum: 40, message: 'を40文字以内で設定してください' }
  validates :introduction, presence: true, length: { maximum: 1000, message: 'を1000文字以内で設定してください' }
  validates :category, presence: { message: 'を３つ選択してください' }
  validates :item_condition, presence: { message: 'を選択してください' }
  validates :postage_payer, presence: { message: 'を選択してください' }
  validates :prefecture, presence: { message: 'を選択してください' }
  validates :preparation_period, presence: { message: 'を選択してください' }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999, message: 'は300〜9999999円の間で設定してください' } 

  validates :brand_id, length: { maximum: 20 }, allow_blank: true
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :user_check, only: [:new, :create]
  before_action :set_item, except: [:index, :new, :create, :show, :get_category_children, :get_category_grandchildren]

  def index
    @items = Item.includes(:images).where(user: current_user).order('created_at DESC')
    @categories = Item.includes(:images).where(category_id: 1..195).order('created_at DESC')
    @new_items = Item.includes(:images).order('created_at DESC')

  end

  def new
    @item = Item.new
    @item.images.new

    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent_array = Category.where(ancestry: nil)
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_id]).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def show
    @item = Item.find(params[:id])
    @grandchild = Category.find(@item.category_id)
    @child = @grandchild.parent
    @parent = @child.parent
    # @itemcategory = Itemcategory.find(@item.category)
    @itemcondition = Itemcondition.find(@item.item_condition)
    @postage = Postage.find(@item.postage_payer)
    @preparation = Preparation.find(@item.preparation_period)
    @district = District.find(@item.prefecture)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @item.images.new
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    # # カテゴリーデータ取得
    @grandchild = @item.category
    @child = @grandchild.parent
    @parent = @child.parent

    #カテゴリー一覧を作成
    @category = Category.where(ancestry: nil)
    # 紐づく孫カテゴリーの親（子カテゴリー）の一覧を配列で取得
    @category_children = @child.parent.children
    # 紐づく孫カテゴリーの一覧を配列で取得
    @category_grandchildren = @grandchild.parent.children
  end

  def update
    @item = Item.find(params[:id])
    @grandchild = @item.category
    @child = @grandchild.parent
    @parent = @child.parent
    @category = Category.where(ancestry: nil)
    @category_children = @child.parent.children
    @category_grandchildren = @grandchild.parent.children
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :name, 
      :introduction, 
      :category_id, 
      :brand_id, 
      :item_condition, 
      :postage_payer, 
      :prefecture, 
      :preparation_period, 
      :price, 
      :user_id, 
      images_attributes: [:src, :_destroy, :id]
    ).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def user_check
    unless user_signed_in?
      redirect_to new_user_session_path, alert: "ログインしてください"
    end
  end

  #親カテゴリー
  def set_category  
    @category_parent_array = Category.where(ancestry: nil)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
%aside.appBannersArea
  .contents
    %h2.contents__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.contents__text
      今すぐ無料ダウンロード！
    .contents__banners
      = link_to '#' do
        = image_tag 'app-store-logo.svg'
      = link_to '#' do
        = image_tag 'google-play-logo.svg'
.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li
          = link_to '#' do
            会社概要（運営会社）
        %li
          = link_to '#' do
            プライバシーポリシー
        %li
          = link_to '#' do
            FURIMA利用規約
        %li
          = link_to '#' do
            ポイントに関する特約
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          = link_to '#' do
            カテゴリー一覧
        %li
          = link_to '#' do
            ブランド一覧
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul
        %li
          = link_to '#' do
            FURIMAガイド
        %li
          = link_to '#' do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to '#' do
            お知らせ
  .footer__logo
    = link_to '#' do
      = image_tag 'logo-white.png'
  %p © FURIMA
= link_to new_item_path do
  .sellBtn
    %span.sellBtn__text 出品する
    = image_tag "icon_camera.png", class: "sellBtn__icon"

app/views/items/_header.html.haml
%header.pageHeader
  .headerContainer
    .topHeader
      %h1.icon
        = link_to root_path, class: 'icon__furima-logo' do
          = image_tag 'logo.png'
      .searchBlock
        %form
          %input.searchBlock__input{placeholder: "キーワードから探す"}
          %button{"type": "submit"}
            .searchBlock__icon
              = image_tag 'icon-search 1.png'
    .nav
      %ul.leftLists
        %li.leftLists__cattab
          = link_to categories_path, class:'tabA' do
            カテゴリー
        %li.leftLists__bratab
          = link_to '#', class:'tabB' do
            ブランド
      %ul.rightLists
        - if user_signed_in?
          %li.rightLists__login
            = link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'loginBtn'
          %li.rightLists__signup
            .rightLists__item--signup
              = link_to 'マイページ', users_path, class:'signupBtn'
        - else
          %li.rightLists__login
            = link_to 'ログイン', new_user_session_path, class:'loginBtn'
          %li.rightLists__signup
            .rightLists__item--signup
              = link_to '新規会員登録', new_user_registration_path, class:'signupBtn'

app/views/items/_item.html.haml
%li.SellingItemArea
  = link_to item_path(item.id), method: :get do
    .SellingItemArea__src
      = image_tag (item.images[0].src.url), class: "SellingItemArea__src__box"
      - if item.purchase.present?
        .photo_sold
          .photo_sold__inner
            SOLD
      .SellingItemArea__src__price
        ¥
        = item.price
    .SellingItemArea__name
      .SellingItemArea__name__box
        = item.name

app/views/items/_sellitemform.html.haml
.SellProductPage
  = render "devise/registrations/head_logo"
  .SellProductPage__container
    = form_with model: @item, class: "FormArea", local: true  do |f|
      = render "devise/shared/error_messages", model: f.object

      .FormArea__content 
        .FormBlock
          .ImageUploadArea
            .ImageUploadArea__content
              出品画像
              %span.MustDescription
                必須
            %p.description
              最大5枚までアップロードできます
              <br>
              ※下枠をクリックしてアップロード
            
            #image-box.ProductFileContainer
              .imagesArea
                .previewArea
                - if @item.persisted?
                  = @item.images.each_with_index do |image, i|
                    = image_tag image.src.url, data: { index: i }, width: "125", height: '125'
                #previews.inputArea
                  %label{for: "item_images_attributes_i_src", class: "label-box", id: "label-box--i"}

                    = f.fields_for :images, class: "UploadArea" do |image|
                      .js-file_group{"data-index": "#{image.index}"}
                        = image.file_field :src, class: "js-file"
                      - if @item.persisted?
                        = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
                    - if @item.persisted?
                      .js-file_group{"data-index": "#{@item.images.count}"}
                        = file_field_tag :src, name: "item[images_attributes][#{@item.images.count}][src]", class: 'js-file'
        .FormBlock
          .FormGroup
            .FormGroup__content
              商品名
              %span.MustDescription
                必須
            = f.text_field :name, class: "FormGroup__input", placeholder:"40文字まで"
          .FormGroup
            .FormGroup__content
              商品の説明
              %span.MustDescription
                必須
            = f.text_area :introduction, class: "textarea", placeholder:"商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）", cols: "40", rows: "7" 
        .FormBlock
          .FormBlock__title
            商品の詳細
          .FormGroup
            .FormGroup__content
              カテゴリー
              %span.MustDescription
                必須
            .FormGroup__content__category
              = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {include_blank: "---"}, {id: 'parent_category'}
            .FormGroup__content
              ブランド
              %span.FreeDescription
                任意
            = f.text_field :brand_id, class: "FormGroup__input", placeholder:"例）Supreme（20文字まで）"
            .FormGroup__content
              商品の状態
              %span.MustDescription
                必須
            = f.collection_select :item_condition, Itemcondition.all, :id, :name, prompt: "---"

        .FormBlock
          .FormBlock__title
            配送について
          .FormGroup
            .FormGroup__content
              配送料の負担
              %span.MustDescription
                必須
            = f.collection_select :postage_payer, Postage.all, :id, :name, prompt: "---"

          .FormGroup
            .FormGroup__content
              発送元の地域
              %span.MustDescription
                必須
            = f.collection_select :prefecture, District.all, :id, :name, prompt: "---"

          .FormGroup
            .FormGroup__content
              発送までの日数
              %span.MustDescription
                必須
            = f.collection_select :preparation_period, Preparation.all, :id, :name, prompt: "---"
        .FormBlock
          .FormBlock__title
            価格（¥300〜9,999,999）
          .FormGroupB
            .FormGroupB__content
              販売価格
              %span.MustDescription
                必須
            .FormGroupB__inputArea
              %p.unit
                ¥
              = f.number_field :price, class: "FormGroupB__inputArea--contents", min:300 , max:9999999
      .FormArea__footer
        .SubmitArea
          = f.submit '出品する', class: 'SellBtn'
        .BackLinkArea
          = link_to "もどる", items_path, class: "BackToIndex"
  .AccountPage__etc
    = render "devise/registrations/foot_logo"
    

app/views/items/edit.html.haml
-# = render partial: '_sellitemform.html'

.SellProductPage
  = render "devise/registrations/head_logo"
  .SellProductPage__container
    = form_with model: @item, class: "FormArea", local: true  do |f|
      = render "devise/shared/error_messages", model: f.object

      .FormArea__content 
        .FormBlock
          .ImageUploadArea
            .ImageUploadArea__content
              出品画像
              %span.MustDescription
                必須
            %p.description
              最大5枚までアップロードできます
              <br>
              ※下枠をクリックしてアップロード
            
            #image-box.ProductFileContainer
              .imagesArea
                .previewArea
                  - if @item.persisted?
                    - @item.images.each_with_index do |image, i|
                      .preview-block
                        = image_tag image.src.url, data: { index: i }, width: "125", height: '125', class: "preview-box"
                        .js-remove
                          削除

                #previews.inputArea
                  = f.label :"images_attributes_#{@item.images.length}_src", class: "label-box", id: "label-box--#{@item.images.length}" do

                    = f.fields_for :images, class: "UploadArea" do |image|
                      .js-file_group{"data-index": "#{image.index}"}
                        = image.file_field :src, class: "js-file"

                      - if @item.persisted?
                        = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
                    - if @item.persisted?
                      .js-file_group{"data-index": "#{@item.images.count}"}
                        = file_field_tag :src, name: "item[images_attributes][#{@item.images.count}][src]", id: "item_images_attributes_#{@item.images.count}_src", class: 'js-file'
        .FormBlock
          .FormGroup
            .FormGroup__content
              商品名
              %span.MustDescription
                必須
            = f.text_field :name, class: "FormGroup__input", placeholder:"40文字まで"
          .FormGroup
            .FormGroup__content
              商品の説明
              %span.MustDescription
                必須
            = f.text_area :introduction, class: "textarea", placeholder:"商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）", cols: "40", rows: "7" 
        .FormBlock
          .FormBlock__title
            商品の詳細
          .FormGroup
            .FormGroup__content
              カテゴリー
              %span.MustDescription
                必須
            -# 親カテゴリー用
            .FormGroup__content__category
              = f.collection_select :category, Category.where(ancestry: nil), :id, :name, {include_blank: "---", selected: @parent.id}, {id: 'parent_category'} 

              -# 子カテゴリー用
              #children_wrapper.FormGroup__content__category__added
                .FormGroup__content__category1
                  = f.collection_select :category, @category_children, :id, :name, {selected: @child.id}, {class: 'FormGroup__content__category--select', id: 'child_category', name: 'item[category_id]'} 

              -# 孫カテゴリー用
              #grandchildren_wrapper.FormGroup__content__category__added
                .FormGroup__content__category2
                  = f.collection_select :category, @category_grandchildren, :id, :name, {selected: @grandchild.id}, {class: 'FormGroup__content__category__box--select', id: 'grandchild_category', name: 'item[category_id]'}

            .FormGroup__content
              ブランド
              %span.FreeDescription
                任意
            = f.text_field :brand_id, class: "FormGroup__input", placeholder:"例）Supreme（20文字まで）"
            .FormGroup__content
              商品の状態
              %span.MustDescription
                必須
            = f.collection_select :item_condition, Itemcondition.all, :id, :name, prompt: "---"

        .FormBlock
          .FormBlock__title
            配送について
          .FormGroup
            .FormGroup__content
              配送料の負担
              %span.MustDescription
                必須
            = f.collection_select :postage_payer, Postage.all, :id, :name, prompt: "---"

          .FormGroup
            .FormGroup__content
              発送元の地域
              %span.MustDescription
                必須
            = f.collection_select :prefecture, District.all, :id, :name, prompt: "---"

          .FormGroup
            .FormGroup__content
              発送までの日数
              %span.MustDescription
                必須
            = f.collection_select :preparation_period, Preparation.all, :id, :name, prompt: "---"
        .FormBlock
          .FormBlock__title
            価格（¥300〜9,999,999）
          .FormGroupB
            .FormGroupB__content
              販売価格
              %span.MustDescription
                必須
            .FormGroupB__inputArea
              %p.unit
                ¥
              = f.number_field :price, class: "FormGroupB__inputArea--contents", min:300 , max:9999999
      .FormArea__footer
        .SubmitArea
          = f.submit '商品編集を完了する', class: 'SellBtn'
        .BackLinkArea
          = link_to "もどる", items_path, class: "BackToIndex"
  .AccountPage__etc
    = render "devise/registrations/foot_logo"

app/views/items/index.html.haml
%body
  = render "header"
  .mainContainer
    %section.topVisual
      .content
        %h2.content__eyecatch
          人生を変えるフリマアプリ
        %p.content__text
          FURIMAはだれでもかんたんに出品・購入できる
          %br
          フリマアプリです
        .content__banners
          = link_to '#', class: 'appBtn' do
            = image_tag 'app-store-logo.svg'
          = link_to '#', class: 'gooBtn' do
            = image_tag 'google-play-logo.svg'
    %section.serviseIntroduction
      %h2.subtitle
        FURIMAが選ばれる3つの理由
      %ul.reasonsLists
        %li.list
          .list__image
            %span.number 1
            = image_tag 'pict-reason-01.jpg'
          %h3.list__text
            %span ３分
            ですぐに出品
          %p.list__description
            スマホで入力するだけで簡単に出品できる

        %li.list
          .list__image
            %span.number 2
            = image_tag 'pict-reason-02.jpg'
          %h3.list__text
            %span シンプル
            で使いやすい
          %p.list__description
            めんどくさい入力は必要なく、検索も購入もスムーズ！

        %li.list
          .list__image
            %span.number 3
            = image_tag 'pict-reason-03.jpg'
          %h3.list__text
            手数料
            %span 業界最安
          %p.list__description
            最大3%でお得に出品&購入！
    %section.appsDLarea
      .contents
        %h2.subtitle 会員数日本一位
        %p.text
          FURIMAは、フリマアプリで最も人気。
          %br/
          出品・購入回数も業界最多です！
          %br/
          ほしかったあの商品に出会えるかもしれません。
        .banners
          = link_to '#', class: 'appBtn' do
            = image_tag 'app-store-logo.svg'
          = link_to '#', class: 'gooBtn' do
            = image_tag 'google-play-logo.svg'
    %section.serviceFeatures
      %h2.title FURIMAの特徴
      .features
        .feature
          %figure.feature__img
            = image_tag 'icon-01.png'
          %h3.feature__subtitle 簡単に売り買いできる
          %p.feature__detail
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        .feature
          %figure.feature__img
            = image_tag 'icon-03.png'
          %h3.feature__subtitle 売上金は即日振込みに対応
          %p.feature__detail
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        .feature
          %figure.feature__img
            = image_tag 'icon-04.png'
          %h3.feature__subtitle 様々な支払いに対応
          %p.feature__detail
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    - if user_signed_in? 
      %section.pickupField
        %h2.head 現在出品中の商品
        %ul.pickupField__box
          = render @items
    %section.pickupField
      %h2.head ピックアップカテゴリー
      .itemBlock
        .itemHead
          = link_to '#' do
            %h3.title 新規投稿商品
        %ul.pickupField__box
          = render @new_items
    %section.pickupField
      %h2.head ピックアップカテゴリー
      .itemBlock
        .itemHead
          = link_to '#' do
            %h3.title レディース新着アイテム
        %ul.pickupField__box
          = render @categories
  = render "footer"

app/views/items/new.html.haml
= render "sellitemform"

app/views/items/show.html.haml
.header
  = render "header"
  
  .showMain
    .topContent
      .itemBox
        %h2.itemBox__itemName
          = @item.name
        .itemBox__itemImage
          .itemBox__itemImage__mainImage
            = image_tag (@item.images[0].src.url), class:"image-main"
            - if @item.purchase.present?
              .itemBox__itemImage__mainImage__photo_sold
                .itemBox__itemImage__mainImage__photo_sold__inner
                  SOLD
          .itemBox__itemImage__subImage
            - @item.images.each do |image|
              = image_tag (image.src.url), size: '140x87'
          .itemBox__price
            ¥
            = @item.price
          .itemBox__priceDetail
            %span
              (税込)
            %span
              送料込み 
          .itemBox__description
            = @item.introduction
        .itemBox__itemTable
          %table
            %tr.tableTypeA
              %th 出品者
              %td 
                =@item.user.nickname
            %tr.tableTypeB
              %th カテゴリー
              %td 
                %span
                  = @parent.name
                  %br 
                    = @child.name
                    %br 
                    = @grandchild.name
            %tr.tableTypeC
              %th ブランド
              %td 
                =@item.brand_id
            %tr.tableTypeA
              %th 商品の状態
              %td 
                = @itemcondition.name
            %tr.tableTypeA
              %th 配送料の負担
              %td
                = @postage.name
            %tr.tableTypeA
              %th 発送元の地域
              %td
                %span
                  = @district.name
            %tr.tableTypeA
              %th 発送日の目安
              %td
                = @preparation.name

        .itemBox__optionalArea
          .itemBox__optionalArea__likeBtn
            = button_tag type: 'button', class: "likeBtn" do
              %i.fa.fa-star 
                %span お気に入り １            
          .itemBox__optionalArea__reportBtn
            =link_to '#', class: "reportBtn" do
              %i.fas.fa-flag  
                %span 不適切な商品を通報

        .itemBox__selectBtn
          - if user_signed_in? && @item.purchase.present?
            .sold_out_btn 売り切れました
          - elsif user_signed_in? && current_user.id == @item.user_id 
            = link_to '商品の編集', edit_item_path(@item), class: "item-red-btn"
            = link_to '商品を削除', item_path(@item), method: :delete, class: "item-destroy"
          - else
            = link_to '購入画面に進む', new_item_purchase_path(@item.id), class:"item-red-btn", method: :get

        .commentBox
          = form_for '#' do |f|
            .commentBox__newComment
              = f.text_area :comment, class: "newComment", placeholder: ""
            .commentBox__explanation
              %p 相手のことを考え丁寧なコメントを心がけましょう。
              %br 不快な言葉遣いなどは利用制限や退会処分になることがあります。     
            .commentBox__commentBtn
              = button_tag type: 'button', class: "commentBtn" do
                %i.fa.fa-comment コメントする

        .links
          .list
            .backItem
              = link_to '#', class:"backBtn" do
                < 前の商品
            .nextItem
              = link_to '#', class:"nextBtn" do
                後の商品 >
        .relatedItem
          = link_to '#', class:"relatedItem" do
            レディースをもっと見る  

        .productLists
          .productLists__productList
            =link_to '#'do
              .productLists__productList__img
                = image_tag 'beef.jpg', size: '220x150'
              .productLists__productList__body
                %h3.name
                  テスト
                .productLists__productList__body__center
                  .productLists__productList__body__center__price
                    10,000円
                  .productLists__productList__body__center__favorite
                    %i.fa.fa-star
                    １
                %p.tax
                  (税込)
        
          .productLists__productList
            =link_to '#'do
              .productLists__productList__img
                = image_tag 'beef.jpg', size: '220x150'
              .productLists__productList__body
                %h3.name
                  テスト
                .productLists__productList__body__center
                  .productLists__productList__body__center__price
                    10,000円
                  .productLists__productList__body__center__favorite
                    %i.fa.fa-star
                    １
                %p.tax
                  (税込) 
          .productLists__productList
            =link_to '#'do
              .productLists__productList__img
                = image_tag 'beef.jpg', size: '220x150'
              .productLists__productList__body
                %h3.name
                  テスト
                .productLists__productList__body__center
                  .productLists__productList__body__center__price
                    10,000円
                  .productLists__productList__body__center__favorite
                    %i.fa.fa-star
                    １
                %p.tax
                  (税込) 
         
              
  
  = render "footer" 